### ISSUE TITLE
Некорректные стили для темной темы

### ISSUE THREAD

**Issue by undermuz** [TrickyPie/test-task#3]
<img width="1532" alt="image" src="https://github.com/TrickyPie/test-task/assets/6875507/e4443600-3d7d-4ba6-8446-a5ac25bbefc4">

нужно отключить использование темной темы

**Comment by TrickyPie** [comment]
@undermuz
[Исправила добавлением конфига в тему](https://github.com/TrickyPie/test-task/commit/e742fc05498660932d6886ef82137390a7cc57b2)
