### ISSUE TITLE
Изменить поведение при выборе чекбокса

### ISSUE THREAD

**Issue by undermuz** [TrickyPie/test-task#4]
При выборе чекбокса нужно лишь сохранить информацию о его состоянии, а на сервер отправлять при нажатии кнопки "Выбрать"
Индикатор загрузки нужно внедрить в эту же кнопку

**Comment by undermuz** [comment]
@TrickyPie 

>правильно ли я поняла: Заходим на страницу, жмем сверху выбрать к одобрению/отклонению, появляются чекбоксы. Мы выбираем нужные заявки и в момент выбора ничего никуда не отправляется. После выбора чекбоксов жмем внизу на кнопку "Выбрано заявок N" и только тогда отправляются PUT запросы, причем последовательно?

да

>Отправлять запросы, выбранные на текущей странице или выбранные в целом на любых страницах?
на любых
да, смена порядковой страницы не должна сбрасывать состояние выбранных элементов

>Написано индикатор загрузки - надо ли заменить спинер на прогресс бар?
спиннера в элементах не должно быть

>При отправке запросов получается в кнопке "Выбрано заявок N" текст заменяется на прогресс бар?
нужно вывести кнопку со спиннером (встроенная в chakra ui фича кнопки)

**Comment by TrickyPie** [comment]
@undermuz
Исправила #9
