### ISSUE TITLE
Некорректный flex

### ISSUE THREAD

**Issue by undermuz** [TrickyPie/test-task#5]
<img width="538" alt="image" src="https://github.com/TrickyPie/test-task/assets/6875507/c214c12e-d34c-419f-b37c-43dbfe60f385">
Отступы между блоками нужно регулировать стилизацией, а не dom-элеметами

**Comment by TrickyPie** [comment]
@undermuz 
[Убрала ](https://github.com/TrickyPie/test-task/commit/0dff71486eb82ce7f3ed0ae53bf3e392809f961c) все `<Spacer/>` элементы.
