### ISSUE TITLE
Странное использование эффекта

### ISSUE THREAD

**Issue by undermuz** [TrickyPie/test-task#6]
<img width="560" alt="image" src="https://github.com/TrickyPie/test-task/assets/6875507/e663e667-1303-48f8-b1b2-e6b14d23aac2">

Тут сразу две ошибки:
1) Зачем стейт который всегда равен значению из контекста? Он бесполезный
2) Неверное использование паттерна мемоизации: если одно значение получается из другого - нужно использовать useMemo, вместо связки useEffect+useState

**Comment by TrickyPie** [comment]
@undermuz
[Исправила](https://github.com/TrickyPie/test-task/commit/291c42a1e14474a0c1923101d7aab7aaf7af3f54), беру нужные данные из контекста.
