### ISSUE TITLE
Некорректное использование try/catch

### ISSUE THREAD

**Issue by undermuz** [TrickyPie/test-task#7]
<img width="592" alt="image" src="https://github.com/TrickyPie/test-task/assets/6875507/a22b0a7a-ae80-4454-b67e-9bbd4479e4e5">

В данном случае try/catch ничего не привносит в работу кода, он лишний

**Comment by TrickyPie** [comment]
@undermuz 
[Исправила](https://github.com/TrickyPie/test-task/commit/c3dd6b2dc5dde82136811565543841de28f419d5)
