### ISSUE TITLE
Заменить относительные пути на абсолютные

### ISSUE THREAD

**Issue by undermuz** [TrickyPie/test-task#8]
<img width="301" alt="image" src="https://github.com/TrickyPie/test-task/assets/6875507/c79d77d2-879c-4c3b-ae73-f20c0f8e8618">

в tsconfig указан алиас на корень, но он почему то не используется в импортах 

<img width="766" alt="image" src="https://github.com/TrickyPie/test-task/assets/6875507/1fdad4b1-9604-4cb0-8102-b5dc598fe44b">

**Comment by TrickyPie** [comment]
@undermuz 
[Обновила пути](https://github.com/TrickyPie/test-task/commit/e4df8e9a44934183fab78259c3195607e249212e)
